# Generated by Django 2.0.5 on 2018-05-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activaciones',
            fields=[
                ('idActivacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentarios')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionTrabajador',
            fields=[
                ('idCapacitacionTrabajador', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Cliente')),
                ('pais', models.CharField(blank=True, default='Chile', max_length=255, null=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, default='Santiago', max_length=255, null=True, verbose_name='Ciudad')),
                ('comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numeroCalle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero')),
                ('dpto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dpto')),
            ],
        ),
        migrations.CreateModel(
            name='Encargados',
            fields=[
                ('idEncargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, max_length=255, null=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail')),
                ('idCliente', models.ForeignKey(on_delete=models.SET('Cliente eliminado'), to='Eventos.Clientes', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('idEstacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Horas')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_y_hora_instalacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de instalacion')),
                ('fecha_y_hora_desinstalacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de desinstalacion')),
                ('inicio_servicio', models.TimeField(blank=True, null=True, verbose_name='Inicio del servicio')),
                ('fin_servicio', models.TimeField(blank=True, null=True, verbose_name='Fin del servicio')),
                ('pais', models.CharField(blank=True, default='Chile', max_length=255, null=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, default='Santiago', max_length=255, null=True, verbose_name='Ciudad')),
                ('comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numeroCalle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero')),
                ('dpto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dpto')),
                ('idActivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Activaciones', verbose_name='Activación')),
                ('idEncargado', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Persona eliminada'), to='Eventos.Encargados', verbose_name='Encargado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsEstacion',
            fields=[
                ('idItemsEstacion', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('idEstacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Estacion', verbose_name='Estacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPlan',
            fields=[
                ('idItemsPlan', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPlanEvento',
            fields=[
                ('idItemsPlanEvento', models.AutoField(primary_key=True, serialize=False)),
                ('idItemsEstacion', models.ForeignKey(on_delete=models.SET('Item eliminado'), to='Eventos.ItemsEstacion', verbose_name='Evento')),
                ('idItemsPlan', models.ForeignKey(on_delete=models.SET('Item eliminado'), to='Eventos.ItemsPlan', verbose_name='Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar en listado')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesEvento',
            fields=[
                ('idPlanesEvento', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Eventos', verbose_name='Evento')),
                ('idPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.Planes', verbose_name='Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('idTrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('trabajados', models.PositiveSmallIntegerField(default=0, verbose_name='Eventos trabajados')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, max_length=255, null=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadoresEvento',
            fields=[
                ('idTrabajadorEvento', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Eventos', verbose_name='Evento')),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Trabajadores', verbose_name='Trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='itemsplanevento',
            name='idPlanesEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.PlanesEvento', verbose_name='PlanesEvento'),
        ),
        migrations.AddField(
            model_name='itemsplan',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Planes', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='capacitaciontrabajador',
            name='idPlan',
            field=models.ForeignKey(on_delete=models.SET('Eliminado'), to='Eventos.Planes', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='capacitaciontrabajador',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='activaciones',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Clientes', verbose_name='Cliente'),
        ),
    ]
