# Generated by Django 2.0.5 on 2018-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(default='evento test dia 1', max_length=255, verbose_name='Evento'),
        ),
    ]
