# Generated by Django 2.0.5 on 2018-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20180509_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='idActivacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='capacitaciontrabajador',
            name='idCapacitacionTrabajador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='idEncargado',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='idEstacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idEvento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='itemsestacion',
            name='idItemsEstacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='idItemsPlan',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idItemsPlanEvento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='idPlan',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='planesevento',
            name='idPlanesEvento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='idTrabajador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='trabajadoresevento',
            name='idTrabajadorEvento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
