# Generated by Django 2.0.5 on 2018-05-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_auto_20180509_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='dpto',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='numeroCalle',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='pais',
        ),
    ]
