# Generated by Django 2.0.5 on 2018-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_activaciones_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='monto',
            field=models.PositiveIntegerField(verbose_name='Monto de venta'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Evento'),
        ),
    ]
