# Generated by Django 2.0.5 on 2018-06-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_auto_20180607_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='Contactos', to='Eventos.Clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='Contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='Eventos', to='Eventos.Contactos', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='itemsestacion',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsEstacion', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlan', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='ItemsEstacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='ItemsPlanEvento', to='Eventos.ItemsEstacion', verbose_name='Item estación'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='ItemsPlan',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='ItemsPlanEvento', to='Eventos.ItemsPlan', verbose_name='Item plan'),
        ),
        migrations.AlterField(
            model_name='planestrabajador',
            name='Plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanesTrabajador', to='Eventos.Planes', verbose_name='Plan'),
        ),
    ]
