# Generated by Django 2.0.5 on 2018-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_auto_20180509_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
