# Generated by Django 2.0.5 on 2018-05-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_eventos_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='dpto',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='numeroCalle',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='pais',
        ),
    ]
