# Generated by Django 2.0.5 on 2018-06-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_auto_20180607_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsplanevento',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Check'),
        ),
    ]
