# Generated by Django 2.0.5 on 2018-06-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_itemsplanevento_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='Multiple'),
        ),
        migrations.AddField(
            model_name='itemsestacion',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='itemsplan',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
