# Generated by Django 2.0.5 on 2018-06-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0007_auto_20180612_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsestacion',
            name='Item',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='ItemsEstacion', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='Item',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='ItemsPlan', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='ItemsEstacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), related_name='ItemsPlanEvento', to='Eventos.ItemsEstacion', verbose_name='Item estación'),
        ),
    ]
