# Generated by Django 2.0.5 on 2018-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0008_auto_20180612_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsplanevento',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
        migrations.AlterField(
            model_name='activaciones',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='items',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
