# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0008_auto_20180514_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsestacion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsplan',
            name='item',
        ),
        migrations.AlterField(
            model_name='activaciones',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha_y_hora_desinstalacion',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Fecha y hora de desinstalacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha_y_hora_instalacion',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Fecha y hora de instalacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fin_servicio',
            field=models.TimeField(blank=True, default='', null=True, verbose_name='Fin del servicio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idEncargado',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.SET('Persona eliminada'), to='Eventos.Encargados', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='inicio_servicio',
            field=models.TimeField(blank=True, default='', null=True, verbose_name='Inicio del servicio'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='itemsestacion',
            name='idItem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Eventos.Inventario', verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='itemsplan',
            name='idItem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Eventos.Inventario', verbose_name='Inventario'),
        ),
    ]
