# Generated by Django 2.0.5 on 2018-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0009_auto_20180618_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='planesevento',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
    ]
