# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0009_auto_20180516_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsestacion',
            name='idEstacion',
        ),
    ]
