# Generated by Django 2.0.5 on 2018-06-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0010_planesevento_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsplanevento',
            options={'ordering': ['n']},
        ),
        migrations.AlterModelOptions(
            name='planesevento',
            options={'ordering': ['n']},
        ),
    ]
