# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0010_remove_itemsestacion_idestacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estacion',
            new_name='Estaciones',
        ),
    ]
