# Generated by Django 2.0.5 on 2018-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0011_auto_20180619_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planesevento',
            options={},
        ),
        migrations.RemoveField(
            model_name='planesevento',
            name='n',
        ),
        migrations.AddField(
            model_name='planesevento',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
