# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0011_auto_20180517_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsestacion',
            name='idEstacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Eventos.Estaciones', verbose_name='Estación'),
        ),
    ]
