# Generated by Django 2.0.5 on 2018-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0012_auto_20180620_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsplanevento',
            options={'ordering': ['nPlan', 'n']},
        ),
        migrations.AddField(
            model_name='itemsplanevento',
            name='nPlan',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
    ]
