# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0012_itemsestacion_idestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='rut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha_y_hora_desinstalacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de desinstalacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha_y_hora_instalacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de instalacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fin_servicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Fin del servicio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idEncargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Persona eliminada'), to='Eventos.Encargados', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='inicio_servicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio del servicio'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
    ]
