# Generated by Django 2.0.5 on 2018-06-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0013_auto_20180620_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsplanevento',
            options={'ordering': ['PlanesEvento', 'nPlan', 'ItemsPlan', 'nItem']},
        ),
        migrations.AlterModelOptions(
            name='planesevento',
            options={'ordering': ['n']},
        ),
        migrations.RenameField(
            model_name='itemsplanevento',
            old_name='n',
            new_name='nItem',
        ),
        migrations.AddField(
            model_name='planesevento',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
    ]
