# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0013_auto_20180517_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horas',
            field=models.PositiveSmallIntegerField(verbose_name='Horas'),
        ),
    ]
