# Generated by Django 2.0.5 on 2018-06-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0014_auto_20180620_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsestacion',
            options={'ordering': ['n']},
        ),
        migrations.AlterModelOptions(
            name='itemsplan',
            options={'ordering': ['n']},
        ),
        migrations.AddField(
            model_name='itemsestacion',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
        migrations.AddField(
            model_name='itemsplan',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='n'),
        ),
    ]
