# Generated by Django 2.0.5 on 2018-05-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0014_auto_20180517_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activaciones',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='activaciones',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='itemsestacion',
            name='idItem',
        ),
        migrations.RemoveField(
            model_name='itemsplan',
            name='idItem',
        ),
        migrations.AddField(
            model_name='activaciones',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activaciones',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Activación'),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsestacion',
            name='idEstacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Estaciones', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idItemsEstacion',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de la estación'), to='Eventos.ItemsEstacion', verbose_name='Item estación'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idItemsPlan',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado del plan'), to='Eventos.ItemsPlan', verbose_name='Item plan'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idPlanesEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.PlanesEvento', verbose_name='#Plan'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Plan'),
        ),
    ]
