# Generated by Django 2.0.5 on 2018-06-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0015_auto_20180620_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsestacion',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsEstacion', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlan', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='ItemsPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlanEvento', to='Eventos.ItemsPlan', verbose_name='Item plan'),
        ),
    ]
