# Generated by Django 2.0.5 on 2018-05-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0015_auto_20180519_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='Items',
        ),
    ]
