# Generated by Django 2.0.5 on 2018-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0016_auto_20180626_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un cargo con este nombre'}, max_length=255, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajadoresevento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un contacto con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una estación con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='items',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un item con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un plan con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este mail'}, max_length=255, null=True, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este RUT'}, max_length=255, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este teléfono'}, max_length=255, null=True, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='trabajadoresevento',
            name='Cargo',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='TrabajadoresEvento', to='Eventos.Cargos', verbose_name='Cargo'),
        ),
    ]
