# Generated by Django 2.0.5 on 2018-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0017_auto_20180519_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsestacion',
            name='idItem',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de Items'), to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='idItem',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de Items'), to='Eventos.Items', verbose_name='Item'),
        ),
    ]
