# Generated by Django 2.0.5 on 2018-05-19 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0018_auto_20180519_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=datetime.date(2018, 5, 19), verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
