# Generated by Django 2.0.5 on 2018-07-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0018_auto_20180628_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una tarea pendiente con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre')),
                ('n', models.PositiveSmallIntegerField(default=1, verbose_name='n')),
            ],
            options={
                'ordering': ['n'],
            },
        ),
        migrations.CreateModel(
            name='PendientesEvento',
            fields=[
                ('idPlanesTrabajador', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendientesEvento', to='Eventos.Eventos', verbose_name='Evento')),
                ('Pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendientesEvento', to='Eventos.Pendientes', verbose_name='Pendientes')),
            ],
        ),
        migrations.CreateModel(
            name='Recurrentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una tarea recurrente con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre')),
                ('n', models.PositiveSmallIntegerField(default=1, verbose_name='n')),
            ],
            options={
                'ordering': ['n'],
            },
        ),
        migrations.CreateModel(
            name='RecurrentesEvento',
            fields=[
                ('idRecurrentesEvento', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecurrentesEvento', to='Eventos.Eventos', verbose_name='Evento')),
                ('Recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecurrentesEvento', to='Eventos.Recurrentes', verbose_name='Recurrentes')),
            ],
        ),
        migrations.AlterField(
            model_name='cargos',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un cargo con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un contacto con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una estación con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='items',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un item con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un plan con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este mail.'}, max_length=255, null=True, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un trabajador con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este RUT.'}, max_length=255, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'Ya existe un trabajador con este teléfono.'}, max_length=255, null=True, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Pendientes',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.PendientesEvento', to='Eventos.Pendientes'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Recurrentes',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.RecurrentesEvento', to='Eventos.Recurrentes'),
        ),
    ]
