# Generated by Django 2.0.5 on 2018-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0019_eventos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='planes',
            field=models.ManyToManyField(through='Eventos.PlanesEvento', to='Eventos.Planes'),
        ),
    ]
