# Generated by Django 2.0.5 on 2018-07-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0019_auto_20180703_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('idPendiente', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una tarea pendiente con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre')),
                ('n', models.PositiveSmallIntegerField(default=1, verbose_name='N°')),
            ],
            options={
                'ordering': ['n'],
            },
        ),
        migrations.CreateModel(
            name='PendientesEvento',
            fields=[
                ('idPlanesTrabajador', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('check', models.BooleanField(default=False, verbose_name='Check')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendientesEvento', to='Eventos.Eventos', verbose_name='Evento')),
                ('Pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendientesEvento', to='Eventos.Pendientes', verbose_name='Pendientes')),
            ],
        ),
        migrations.CreateModel(
            name='Recurrentes',
            fields=[
                ('idRecurrente', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una tarea recurrente con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre')),
                ('n', models.PositiveSmallIntegerField(default=1, verbose_name='N°')),
            ],
            options={
                'ordering': ['n'],
            },
        ),
        migrations.CreateModel(
            name='RecurrentesEvento',
            fields=[
                ('idRecurrentesEvento', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('check', models.BooleanField(default=False, verbose_name='Check')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecurrentesEvento', to='Eventos.Eventos', verbose_name='Evento')),
                ('Recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecurrentesEvento', to='Eventos.Recurrentes', verbose_name='Recurrentes')),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='Pendientes',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.PendientesEvento', to='Eventos.Pendientes'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Recurrentes',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.RecurrentesEvento', to='Eventos.Recurrentes'),
        ),
    ]
