# Generated by Django 2.0.5 on 2018-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0019_auto_20180703_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendientes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recurrentes',
            name='id',
        ),
        migrations.AddField(
            model_name='pendientes',
            name='idPendiente',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='#'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrentes',
            name='idRecurrente',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='#'),
            preserve_default=False,
        ),
    ]
