# Generated by Django 2.0.5 on 2018-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0020_auto_20180703_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendientesevento',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Check'),
        ),
        migrations.AddField(
            model_name='recurrentesevento',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Check'),
        ),
    ]
