# Generated by Django 2.0.5 on 2018-05-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0020_eventos_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='items',
            field=models.ManyToManyField(through='Eventos.ItemsPlan', to='Eventos.Items'),
        ),
    ]
