# Generated by Django 2.0.5 on 2018-07-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0020_auto_20180703_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['fecha', 'Activacion']},
        ),
        migrations.AddField(
            model_name='eventos',
            name='estado',
            field=models.CharField(default='Coordinación', max_length=255, verbose_name='Estado'),
        ),
    ]
