# Generated by Django 2.0.5 on 2018-07-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0021_auto_20180706_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='Contactos', to='Eventos.Clientes', verbose_name='Cliente'),
        ),
    ]
