# Generated by Django 2.0.5 on 2018-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0021_planes_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaciones',
            name='items',
            field=models.ManyToManyField(through='Eventos.ItemsEstacion', to='Eventos.Items'),
        ),
        migrations.AddField(
            model_name='itemsplan',
            name='itemsEstacion',
            field=models.ManyToManyField(through='Eventos.ItemsPlanEvento', to='Eventos.ItemsEstacion'),
        ),
        migrations.AddField(
            model_name='planesevento',
            name='itemsEstacion',
            field=models.ManyToManyField(through='Eventos.ItemsPlanEvento', to='Eventos.ItemsEstacion'),
        ),
        migrations.AddField(
            model_name='planesevento',
            name='itemsPlan',
            field=models.ManyToManyField(through='Eventos.ItemsPlanEvento', to='Eventos.ItemsPlan'),
        ),
    ]
