# Generated by Django 2.0.5 on 2018-07-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0021_auto_20180703_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'ordering': ['n']},
        ),
        migrations.AddField(
            model_name='cargos',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='recurrentes',
            name='n',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='N°'),
        ),
    ]
