# Generated by Django 2.0.5 on 2018-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0022_auto_20180706_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='comentarios_satisfaccion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comentarios Satisfacción'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='satisfaccion',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Satisfacción'),
        ),
    ]
