# Generated by Django 2.0.5 on 2018-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0022_auto_20180523_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
