# Generated by Django 2.0.5 on 2018-07-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0024_auto_20180706_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='satisfaccion',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Satisfacción'),
        ),
    ]
