# Generated by Django 2.0.5 on 2018-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0024_auto_20180524_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='trabajadores',
            field=models.ManyToManyField(through='Eventos.PlanesTrabajador', to='Eventos.Trabajadores'),
        ),
    ]
