# Generated by Django 2.0.5 on 2018-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0025_auto_20180706_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='errores_tecnicos',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Errores técnicos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='comentarios_satisfaccion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comentarios satisfacción'),
        ),
    ]
