# Generated by Django 2.0.5 on 2018-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0025_planes_trabajadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activaciones', to='Eventos.Clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='idCliente',
            field=models.ForeignKey(on_delete=models.SET('Cliente eliminado'), related_name='Encargados', to='Eventos.Clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='encargados',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='items',
            field=models.ManyToManyField(related_name='Estaciones', through='Eventos.ItemsEstacion', to='Eventos.Items'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idActivacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='Eventos.Activaciones', verbose_name='Activación'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idEncargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Persona eliminada'), related_name='Eventos', to='Eventos.Encargados', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='planes',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.PlanesEvento', to='Eventos.Planes'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='trabajadores',
            field=models.ManyToManyField(related_name='Eventos', through='Eventos.TrabajadoresEvento', to='Eventos.Trabajadores'),
        ),
        migrations.AlterField(
            model_name='itemsestacion',
            name='idEstacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsEstacion', to='Eventos.Estaciones', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='itemsestacion',
            name='idItem',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de Items'), related_name='ItemsEstacion', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='idItem',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de Items'), related_name='ItemsPlan', to='Eventos.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlan', to='Eventos.Planes', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='itemsplan',
            name='itemsEstacion',
            field=models.ManyToManyField(related_name='ItemsPlan', through='Eventos.ItemsPlanEvento', to='Eventos.ItemsEstacion'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idItemsEstacion',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado de la estación'), related_name='ItemsPlanEvento', to='Eventos.ItemsEstacion', verbose_name='Item estación'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idItemsPlan',
            field=models.ForeignKey(on_delete=models.SET('Item eliminado del plan'), related_name='ItemsPlanEvento', to='Eventos.ItemsPlan', verbose_name='Item plan'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='idPlanesEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlanEvento', to='Eventos.PlanesEvento', verbose_name='#Plan'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='items',
            field=models.ManyToManyField(related_name='Planes', through='Eventos.ItemsPlan', to='Eventos.Items'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='trabajadores',
            field=models.ManyToManyField(related_name='Planes', through='Eventos.PlanesTrabajador', to='Eventos.Trabajadores'),
        ),
        migrations.AlterField(
            model_name='planesevento',
            name='idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanesEvento', to='Eventos.Eventos', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='planesevento',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PlanesEvento', to='Eventos.Planes', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='planesevento',
            name='itemsEstacion',
            field=models.ManyToManyField(related_name='PlanesEvento', through='Eventos.ItemsPlanEvento', to='Eventos.ItemsEstacion'),
        ),
        migrations.AlterField(
            model_name='planesevento',
            name='itemsPlan',
            field=models.ManyToManyField(related_name='PlanesEvento', through='Eventos.ItemsPlanEvento', to='Eventos.ItemsPlan'),
        ),
        migrations.AlterField(
            model_name='planestrabajador',
            name='idPlan',
            field=models.ForeignKey(on_delete=models.SET('Eliminado'), related_name='PlanesTrabajador', to='Eventos.Planes', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='planestrabajador',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanesTrabajador', to='Eventos.Trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='trabajadoresevento',
            name='idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrabajadoresEvento', to='Eventos.Eventos', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='trabajadoresevento',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrabajadoresEvento', to='Eventos.Trabajadores', verbose_name='Trabajador'),
        ),
    ]
