# Generated by Django 2.0.5 on 2018-07-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0026_auto_20180706_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('idError', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('error', models.TextField(blank=True, default='', null=True, verbose_name='Errores técnicos')),
            ],
        ),
        migrations.AlterModelOptions(
            name='activaciones',
            options={'ordering': ['-idActivacion']},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['-idCliente']},
        ),
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['-idContacto']},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-idEvento', '-Activacion']},
        ),
        migrations.AlterModelOptions(
            name='trabajadores',
            options={'ordering': ['-idTrabajador']},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='errores_tecnicos',
        ),
        migrations.AddField(
            model_name='errores',
            name='Evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Errores', to='Eventos.Eventos', verbose_name='Evento'),
        ),
    ]
