# Generated by Django 2.0.5 on 2018-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0026_auto_20180524_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_y_hora_desinstalacion',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='fecha_y_hora_instalacion',
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_desinstalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de desinstalacion'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de instalacion'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_desinstalacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de desinstalacion'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_instalacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de instalacion'),
        ),
    ]
