# Generated by Django 2.0.5 on 2018-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0029_auto_20180710_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activaciones',
            name='monto',
        ),
        migrations.AddField(
            model_name='activaciones',
            name='tipo',
            field=models.CharField(choices=[['Pixz', 'Pixz'], ['Weddi', 'Weddi'], ['Producción', 'Producción'], ['Tech', 'Tech']], default='Pixz', max_length=255, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturas',
            name='fecha_pago',
            field=models.DateField(null=True, verbose_name='Fecha de pago'),
        ),
    ]
