# Generated by Django 2.0.5 on 2018-05-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0029_auto_20180528_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='idEncargado',
            new_name='Encargado',
        ),
    ]
