# Generated by Django 2.0.5 on 2018-07-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0030_auto_20180711_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
