# Generated by Django 2.0.5 on 2018-07-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0031_auto_20180711_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='nFactura',
            field=models.PositiveIntegerField(error_messages={'unique': 'Ya existe este número de factura.'}, primary_key=True, serialize=False, unique=True, verbose_name='N° de factura'),
        ),
    ]
