# Generated by Django 2.0.5 on 2018-05-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0031_auto_20180528_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargados',
            old_name='idCliente',
            new_name='Cliente',
        ),
    ]
