# Generated by Django 2.0.5 on 2018-05-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0032_auto_20180528_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='trabajados',
        ),
    ]
