# Generated by Django 2.0.5 on 2018-07-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0032_auto_20180711_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
