# Generated by Django 2.0.5 on 2018-05-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0033_remove_trabajadores_trabajados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadoresevento',
            old_name='idTrabajador',
            new_name='Trabajador',
        ),
    ]
