# Generated by Django 2.0.5 on 2018-07-11 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0033_auto_20180711_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='plazo',
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_pago',
            field=models.DateField(default=datetime.date(2018, 7, 11), verbose_name='Fecha de pago'),
            preserve_default=False,
        ),
    ]
