# Generated by Django 2.0.5 on 2018-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0034_auto_20180711_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-idEvento']},
        ),
        migrations.AddField(
            model_name='activaciones',
            name='adelanto',
            field=models.PositiveIntegerField(default=0, verbose_name='Adelanto'),
        ),
        migrations.AddField(
            model_name='activaciones',
            name='monto',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto de venta'),
            preserve_default=False,
        ),
    ]
