# Generated by Django 2.0.5 on 2018-05-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0034_auto_20180528_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadoresevento',
            old_name='idEvento',
            new_name='Evento',
        ),
    ]
