# Generated by Django 2.0.5 on 2018-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0036_remove_facturas_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estado',
            field=models.IntegerField(default=0, verbose_name='Estado'),
        ),
    ]
