# Generated by Django 2.0.5 on 2018-07-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0038_eventos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='seguimiento_desinstalacion',
            field=models.TextField(default='', verbose_name='Estado desmontaje'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='seguimiento_instalacion',
            field=models.TextField(default='', verbose_name='Estado montaje'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='seguimiento_servicio',
            field=models.TextField(default='', verbose_name='Estado servicio'),
        ),
    ]
