# Generated by Django 2.0.5 on 2018-05-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0038_auto_20180528_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planesevento',
            old_name='idPlan',
            new_name='Plan',
        ),
    ]
