# Generated by Django 2.0.5 on 2018-05-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0039_auto_20180528_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planesevento',
            old_name='itemsPlan',
            new_name='ItemsPlan',
        ),
    ]
