# Generated by Django 2.0.5 on 2018-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0039_auto_20180724_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='seguimiento_servicio',
        ),
        migrations.AddField(
            model_name='eventos',
            name='seguimiento_fin_servicio',
            field=models.TextField(default='', verbose_name='Estado fin de servicio'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='seguimiento_inicio_servicio',
            field=models.TextField(default='', verbose_name='Estado inicio de servicio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='seguimiento_desinstalacion',
            field=models.TextField(default='', verbose_name='Estado desinstalación'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='seguimiento_instalacion',
            field=models.TextField(default='', verbose_name='Estado instalación'),
        ),
    ]
