# Generated by Django 2.0.5 on 2018-08-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0040_auto_20180724_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errores',
            options={'ordering': ['-idError']},
        ),
        migrations.AlterModelOptions(
            name='facturas',
            options={'ordering': ['-nFactura']},
        ),
    ]
