# Generated by Django 2.0.5 on 2018-08-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0041_auto_20180805_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('idIngreso', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('Activacion', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='Ingresos', to='Eventos.Activaciones', verbose_name='Activacion')),
                ('Factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ingresos', to='Eventos.Facturas', verbose_name='Factura')),
            ],
        ),
    ]
