# Generated by Django 2.0.5 on 2018-05-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0041_auto_20180528_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsplanevento',
            old_name='idPlanesEvento',
            new_name='PlanesEvento',
        ),
    ]
