# Generated by Django 2.0.5 on 2018-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0042_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comentarios'),
        ),
    ]
