# Generated by Django 2.0.5 on 2018-08-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0043_ingresos_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activaciones',
            name='adelanto',
        ),
    ]
