# Generated by Django 2.0.5 on 2018-08-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0044_remove_activaciones_adelanto'),
    ]

    operations = [
        migrations.AddField(
            model_name='activaciones',
            name='montoIVA',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto con IVA'),
            preserve_default=False,
        ),
    ]
