# Generated by Django 2.0.5 on 2018-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0046_facturas_montoiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosVariables',
            fields=[
                ('idCostoVariable', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('documento', models.TextField(verbose_name='Documento')),
                ('tipo', models.TextField(blank=True, null=True, verbose_name='Tipo')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentarios', models.TextField(blank=True, default='', null=True, verbose_name='Comentarios')),
                ('Evento', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='CostosVariables', to='Eventos.Eventos', verbose_name='Evento')),
            ],
        ),
    ]
