# Generated by Django 2.0.5 on 2018-08-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0047_costosvariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCostoVariable',
            fields=[
                ('idTipoCostoVariable', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un costo variable con este nombre.'}, max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='costosvariables',
            name='tipo',
        ),
        migrations.AddField(
            model_name='costosvariables',
            name='Tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='CostosVariables', to='Eventos.TiposCostoVariable', verbose_name='Tipo'),
        ),
    ]
