# Generated by Django 2.0.5 on 2018-05-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0047_auto_20180528_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsplan',
            old_name='idItem',
            new_name='Item',
        ),
    ]
