# Generated by Django 2.0.5 on 2018-09-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0050_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='User',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
