# Generated by Django 2.0.5 on 2018-09-30 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eventos', '0051_auto_20180930_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='freelance', max_length=255, verbose_name='Tipo de usuario')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TipoUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Tipo de usuario')),
            ],
        ),
    ]
