# Generated by Django 2.0.5 on 2018-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0052_auto_20180528_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Teléfono'),
        ),
    ]
