# Generated by Django 2.0.5 on 2019-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0052_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='errores',
            name='resuelto',
            field=models.BooleanField(default=False, verbose_name='Resuelto'),
        ),
    ]
