# Generated by Django 2.0.5 on 2019-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0053_errores_resuelto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('idMeta', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('mes', models.DateField(error_messages={'unique': 'Ya existe una meta para este mes.'}, unique=True, verbose_name='Mes')),
                ('meta', models.PositiveIntegerField(default=0, verbose_name='Meta')),
            ],
            options={
                'ordering': ['-mes'],
            },
        ),
    ]
