# Generated by Django 2.0.5 on 2018-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0053_auto_20180528_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='Mail'),
        ),
    ]
