# Generated by Django 2.0.5 on 2018-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0054_auto_20180529_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargados',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Mail'),
        ),
    ]
