# Generated by Django 2.0.5 on 2018-05-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0055_auto_20180529_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un trabajador con este nombre'}, max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
