# Generated by Django 2.0.5 on 2018-05-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0056_auto_20180529_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='trabajadores',
            new_name='Trabajadores',
        ),
    ]
