# Generated by Django 2.0.5 on 2018-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0057_auto_20180529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
