# Generated by Django 2.0.5 on 2018-05-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0060_auto_20180529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comentarios'),
        ),
    ]
