# Generated by Django 2.0.5 on 2018-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0061_auto_20180529_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadoresevento',
            name='tipo',
            field=models.CharField(default='', max_length=255, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
