# Generated by Django 2.0.5 on 2018-06-02 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0062_trabajadoresevento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsplanevento',
            name='ItemsEstacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Item eliminado de la estación'), related_name='ItemsPlanEvento', to='Eventos.ItemsEstacion', verbose_name='Item estación'),
        ),
        migrations.AlterField(
            model_name='itemsplanevento',
            name='PlanesEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPlanEvento', to='Eventos.PlanesEvento', verbose_name='Plan evento'),
        ),
    ]
