# Generated by Django 2.0.5 on 2018-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0063_auto_20180601_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Mail')),
                ('Cliente', models.ForeignKey(on_delete=models.SET('Cliente eliminado'), related_name='Contactos', to='Eventos.Clientes', verbose_name='Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='Encargado',
        ),
        migrations.AddField(
            model_name='eventos',
            name='Contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Persona eliminada'), related_name='Eventos', to='Eventos.Contactos', verbose_name='Contacto'),
        ),
    ]
