# Generated by Django 2.0.5 on 2018-06-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0065_auto_20180604_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='rut',
        ),
    ]
